// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ===== WEB =====
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcBzVasfHH3Dxryhb29Z-55M-gvZ7sFLo',
    appId: '1:439081069385:web:e172f2c74a4f2d7f2e4898',
    messagingSenderId: '439081069385',
    projectId: 'soul-chaser-4a10c',
    authDomain: 'soul-chaser-4a10c.firebaseapp.com',
    storageBucket: 'soul-chaser-4a10c.firebasestorage.app',
    measurementId: 'G-FS34FXBHZZ',
  );

  // ===== ANDROID =====
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqbys0_mf2v_8YvGcDYMnWWZh-soFjzbg',
    appId: '1:439081069385:android:2ca097cd8708da8d2e4898',
    messagingSenderId: '439081069385',
    projectId: 'soul-chaser-4a10c',
    storageBucket: 'soul-chaser-4a10c.appspot.com',
  );

  // ===== iOS =====
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbys0_mf2v_8YvGcDYMnWWZh-soFjzbg',
    appId: '1:439081069385:ios:403e968fa3d468ce2e4898',
    messagingSenderId: '439081069385',
    projectId: 'soul-chaser-4a10c',
    storageBucket: 'soul-chaser-4a10c.appspot.com',
    iosClientId: '403e968fa3d468ce2e4898',
    iosBundleId: 'com.example.soulChaserFlutter',
  );

  // ===== macOS =====
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbys0_mf2v_8YvGcDYMnWWZh-soFjzbg',
    appId: '1:439081069385:macos:REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: '439081069385',
    projectId: 'soul-chaser-4a10c',
    storageBucket: 'soul-chaser-4a10c.appspot.com',
  );

  // ===== Windows =====
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqbys0_mf2v_8YvGcDYMnWWZh-soFjzbg',
    appId: '1:439081069385:windows:REPLACE_WITH_YOUR_WINDOWS_APP_ID',
    messagingSenderId: '439081069385',
    projectId: 'soul-chaser-4a10c',
    storageBucket: 'soul-chaser-4a10c.appspot.com',
  );
}
